# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel caches
        uses: actions/cache@v2
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: bazel-cache-
      - name: bazel test //...
        env:
          # Bazelisk will download bazel to here
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: |
          bazel \
            --bazelrc=.github/workflows/ci.bazelrc \
            --bazelrc=.bazelrc \
            test \
            --disk_cache=${HOME}/.cache/bazel \
            --repository_cache=${HOME}/.cache/bazel-repo \
            //...
      - name: Rename release artifact with version
        run: cp $(ls bazel-out/*/bin/*.tar.gz | tail -1) "rules_container-$(git describe --tags | sed 's/^v//').tar.gz"
      # TODO: move this into bazel to produce the file with expand_template rule when it has stamping
      - name: Prepare workspace snippet
        run: |
          echo -e "WORKSPACE snippet:\n\n\`\`\`starlark\nhttp_archive(\n    name = \"rules_container\"," > release_notes.txt
          echo "    sha256 = \"$(shasum -a 256 *.tar.gz | awk '{print $1}')\"," >> release_notes.txt
          echo -e "    url = \"https://github.com/thesayyn/rules_container/releases/download/$(git describe --tags)/$(ls *.tar.gz)\",\n)\n\`\`\`" >> release_notes.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: release_notes.txt
          files: "*.tar.gz"
